### ISSUE TITLE
Keep getting "E: Unable to locate package ros-melodic-flir-camera-description"

### ISSUE THREAD

**Issue by fyusufzai88** [Tinker-Twins/Husky#5]
I am running melodic not noetic and every other dependency is working but this one. It is preventing me from running roslaunch and I just need the correct dependency.

**Comment by Tinker-Twins** [comment]
Unfortunately, as per [ROS Index](https://index.ros.org/p/flir_camera_description), the `flir_camera_description` package is not available for ROS Melodic. You can try building [this package](https://github.com/ros-drivers/flir_camera_driver/tree/noetic-devel/flir_camera_description) from source using the [official repository](https://github.com/ros-drivers/flir_camera_driver). Again, you will not find `melodic-devel` branch but the `noetic-devel` branch should most likely work. That being said, ROS Melodic has recently reached its EOL and it is highly recommended to switch to ROS Noetic.
